---
- name: Create, mount, and print disk usage of XFS filesystem on LVM
  hosts: all
  become: yes

  vars_prompt:
    - name: "vg_name"
      prompt: "Enter the Volume Group (VG) name"
      private: no

    - name: "lv_name"
      prompt: "Enter the Logical Volume (LV) name"
      private: no

    - name: "mount_point"
      prompt: "Enter the mount point directory (e.g., /data)"
      private: no

    - name: "lv_size"
      prompt: "Enter the size of the logical volume (e.g., 2G)"
      private: no

  tasks:
    - name: Ensure xfsprogs is installed
      package:
        name: xfsprogs
        state: present

    - name: Check if Volume Group exists
      command: vgdisplay "{{ vg_name }}"
      register: vg_check
      ignore_errors: yes
      changed_when: false

    - name: Fail if VG does not exist
      fail:
        msg: "The Volume Group '{{ vg_name }}' does not exist. Please create it first."
      when: vg_check.rc != 0

    - name: Create logical volume
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: "{{ lv_size }}"
        state: present

    - name: Check if filesystem already exists on LV
      command: blkid "/dev/{{ vg_name }}/{{ lv_name }}"
      register: fs_check
      ignore_errors: yes
      changed_when: false

    - name: Fail if filesystem already exists
      fail:
        msg: "Filesystem already exists on /dev/{{ vg_name }}/{{ lv_name }}. Skipping creation to avoid overwrite."
      when: fs_check.rc == 0

    - name: Create XFS filesystem
      filesystem:
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ lv_name }}"
      when: fs_check.rc != 0

    - name: Create mount point directory
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Mount logical volume
      mount:
        path: "{{ mount_point }}"
        src: "/dev/{{ vg_name }}/{{ lv_name }}"
        fstype: xfs
        state: mounted

    - name: Ensure fstab entry exists
      mount:
        path: "{{ mount_point }}"
        src: "/dev/{{ vg_name }}/{{ lv_name }}"
        fstype: xfs
        opts: defaults
        state: present

    - name: Show disk usage for the mount point
      command: df -h "{{ mount_point }}"
      register: df_output
      changed_when: false

    - name: Display df output
      debug:
        msg: "{{ df_output.stdout }}"
