---
- name: Collect installed RPMs as JSON
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Get installed RPM packages
      shell: rpm -qa --qf '{"name":"%{NAME}","version":"%{VERSION}-%{RELEASE}","arch":"%{ARCH}"}\n'
      register: rpm_output
      
    - name: Create JSON fact from RPM output
      set_fact:
        installed_rpms: "{{ rpm_output.stdout_lines | map('from_json') | list }}"
        
    - name: Save RPM facts to file
      copy:
        content: "{{ installed_rpms | to_nice_json }}"
        dest: "/tmp/installedrpms{{ inventory_hostname }}.json"
