---
- name: Reboot the server
  hosts: all
  become: yes
  gather_facts: true 

  tasks:

    - name: Set reboot timeout based on virtualization type
      set_fact:
        reboot_timeout: "{{ 600 if ansible_facts.virtualization_type != 'NA' else 1500 }}"   

    - name: Reboot the server and wait for it to come back
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"   
        test_command: uptime

    - name: Debug message that server is up
      ansible.builtin.debug:
        msg: "Server {{ inventory_hostname }} is up & running"
