---
- name: Collect vg00 info and generate CSV
  hosts: all
  gather_facts: false

  tasks:
    - name: Get vg00 information
      shell: vgs --no-headings --units g --nosuffix -o vg_name,vg_free vg00  | awk -v h=$(hostname) '{print h "," $1 "," $2}'
      register: vg_output
      changed_when: false
      failed_when: false

    - name: Append result to CSV on control node
      lineinfile:
        path: /tmp/vg00_report_all.csv
        create: yes
        line: "{{ vg_output.stdout }}"
        insertafter: EOF
      delegate_to: localhost
