- name: Gather packages with full details and save JSON per host
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather package facts
      package_facts:

    - name: Save package facts JSON on control node per host
      copy:
        content: "{{ ansible_facts.packages | to_nice_json }}"
        dest: "/var/opt/reports/{{ inventory_hostname }}.rpt"
      delegate_to: localhost
